### ISSUE TITLE
[Feature Request] Enable easy interactive shell on a container.

### ISSUE THREAD

**Issue by Tarektouati** [pyaillet/doggy#22]
Hey ! 

Like modern Containers UI admin panel, 

Through the listing UI, other wither than delete the container, We can also have a command to executes an interactive shell on the container.

This would avoid that, `docker ps` `docker exec -it <CONTAINER_ID> /bin/sh`  and keep user in doggy.

Thanks

**Comment by pyaillet** [comment]
Hi !
Thanks for your interest, it's already implemented.
If you type `s` it will launch `/bin/bash` in the container.
However, error handling (linked to #9) and changing for another command is not yet supported and could be a nice addition.

**Comment by Tarektouati** [comment]
@pyaillet  Actually supporting another command than the default `/bin/bash`

**Comment by pyaillet** [comment]
Fixed by #26 and #9 is taken care of too!

I am preparing a v0.2.0 with these

**Comment by pyaillet** [comment]
You can check [here](https://github.com/pyaillet/doggy/releases/tag/v0.2.0) if you want to test it.
Use `Shift+S` to launch a custom command.

**Comment by pyaillet** [comment]
@Tarektouati It's OK for now. I'll close this issue.

Feel free to reopen it (or another one) if needed.
