### ISSUE TITLE
Installation with homebrew doesn't seem to work

### ISSUE THREAD

**Issue by Gudsfile** [pyaillet/doggy#76]
Installation with homebrew doesn't seem to work (i'm on darwin arm64).

```shell
$ brew tap pyaillet/homebrew-formulas
$ brew install pyaillet/doggy
Warning: No available formula with the name "doggy". Did you mean doggo or dog?
==> Searching for similarly named formulae and casks...
==> Formulae
doggo                                                                        dog

To install doggo, run:
  brew install doggo
```

**Comment by pyaillet** [comment]
Thanks for reporting this. I can reproduce this problem.

I'll let you know when it's fixed.

**Comment by pyaillet** [comment]
You should be able to install it now, just make sure to launch the following commands:
```
brew untap pyaillet/homebrew-formulas
brew tap pyaillet/homebrew-formulas
brew install pyaillet/doggy
```

**Comment by noancloarec** [comment]
I had to use `brew install pyaillet/formulas/doggy` instead of `brew install pyaillet/doggy` (5 minutes ago).  
On Ubuntu 22.04

**Comment by pyaillet** [comment]
I had to change the topology of the formula repository. I will check if the instructions need to be different between MacOS and Linux and update them accordingly.

**Comment by Gudsfile** [comment]
I had to use `brew install pyaillet/formulas/doggy` too (2 minutes ago). (On MacOs 14.4)

**Comment by pyaillet** [comment]
Ok, I'll change the instructions then!
Thanks for the feedback.
